config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
  }
  #devise_for :users, controllers: {
  # registrations: 'users/registrations'
  # }
  devise_scope :user do
  get "users/sign_in", :to => "devise/sessions#new"
  get "users/sign_out", :to => "devise/sessions#destroy"
  end
  root 'home#top'
  # get "/" => "home#top"
  get "member/:id/edit" => "member#edit"
  post "member/:id/update" => "member#update"
  get "home/user_info" => "home#user_info"
  get 'posts/index'
  get "posts/new" => "posts#new"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/update" => "posts#update"
  post "posts/:id/destroy" => "posts#destroy"
  get "posts/:id" => "posts#show"
  get 'home/index'
  get 'home/authentication'
  get "profile/edit" => "profile#edit"
  post "profile/:id/update" => "profile#update"
  get "community/index" => "community#index"
  get "community/new" => "community#new"
  post "community/create" => "community#create"
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: '/letter_opener'
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => {
  # :registrations => 'users/registrations',
  # :sessions => 'users/sessions'
  # }

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   get "sign_out", :to => "users/sessions#destroy"
  # end

end

app/models/community.rb
class Community < ApplicationRecord
  mount_uploader :community_pic, ImageUploader

  def self.search(search)
  if search
    Community.where(['(description LIKE ?) OR (community_name LIKE ?)', "%#{search}%", "%#{search}%"])
  else
    Community.all
  end
end
end

app/controllers/community_controller.rb
class CommunityController < ApplicationController

  layout 'community_app.html.erb'

  def index
    @community = Community.search(params[:search])
    @community = @community.page(params[:page]).per(5)
  end

  def new
  end

  def create
    @community = Community.new(community_name: params[:community_name],region: params[:prefucture],description: params[:content],community_pic: params[:image_name],daihyo_id: current_user.id)
    if @community.save
      @users = User.find_by(id: current_user.id)
      @users.community_id = @community.id
      if @users.save
        flash[:notice] = "更新に成功しました。"
        redirect_to("/community/index")
      else
        flash[:notice] = "更新に失敗しました。"
        render("community/new")
      end
    else
      flash[:notice] = "更新に失敗しました。"
      render("community/new")
    end
  end

end

app/helpers/community_helper.rb
module CommunityHelper
end

app/views/community/index.html.erb
<%= stylesheet_link_tag 'community', :media => "all" %>
<%= render 'shared/community_helper' %>

<%@community.each do |communities|%>
  <div class="">
    <%="コミュニティ名：#{communities.community_name}"%>
  </div>
  <div class="">
    <%="地域：#{communities.region}"%>
  </div>
  <div class="">
    <%="コミュニティ説明：#{communities.description}"%>
  </div>
  <div class="">
    <img src=<%= communities.community_pic %>>
  </div>
<%end%>
<%= paginate @community -%>
<%="community index"%>

app/views/community/new.html.erb
<%= stylesheet_link_tag 'community', :media => "all" %>
<%= render 'shared/community_helper' %>
<h1 class="title">コミュニティ新規登録</h1>

<div class="container_oya">
    <div class="container_community_new">
      <div class="community_outside_new">
      <%= form_with url: community_create_path do |f| %>
        <!--コミュニティ名入力-->
        <div class="field">
          <div class="community_name_label">
            <%= f.label :コミュニティ名 %><br />
          </div>
          <div class="community_name_input_outside">
            <div class="community_name_input_inner">
              <%= f.text_field :community_name%>
            </div>
          </div>
        </div>
        <!--地域選択-->
        <div class="field">
          <div class="region_name_label">
            <%= f.label :地域 %><br />
          </div>
          <div class="region_input_outside">
            <div class="region_input_inner">
              <%= f.select :prefucture ,
                { 北海道: "北海道" ,
                青森県: "青森県" ,
                岩手県: "岩手県" ,
                宮城県: "宮城県" ,
                秋田県: "秋田県" ,
                山形県: "山形県" ,
                福島県: "福島県" ,
                茨城県: "茨城県" ,
                栃木県: "栃木県" ,
                群馬県: "群馬県" ,
                埼玉県: "埼玉県" ,
                千葉県: "千葉県" ,
                東京都: "東京都" ,
                神奈川県: "神奈川県" ,
                新潟県: "新潟県" ,
                富山県: "富山県" ,
                石川県: "石川県" ,
                福井県: "福井県" ,
                山梨県: "山梨県" ,
                長野県: "長野県" ,
                岐阜県: "岐阜県" ,
                静岡県: "静岡県" ,
                愛知県: "愛知県" ,
                三重県: "三重県" ,
                滋賀県: "滋賀県" ,
                京都府: "京都府" ,
                大阪府: "大阪府" ,
                兵庫県: "兵庫県" ,
                奈良県: "奈良県" ,
                和歌山県: "和歌山県" ,
                鳥取県: "鳥取県" ,
                島根県: "島根県" ,
                岡山県: "岡山県" ,
                広島県: "広島県" ,
                山口県: "山口県" ,
                徳島県: "徳島県" ,
                香川県: "香川県" ,
                愛媛県: "愛媛県" ,
                高知県: "高知県" ,
                福岡県: "福岡県" ,
                佐賀県: "佐賀県" ,
                長崎県: "長崎県" ,
                熊本県: "熊本県" ,
                大分県: "大分県" ,
                宮崎県: "宮崎県" ,
                鹿児島県: "鹿児島県" ,
                沖縄県: "沖縄県" ,
                海外: "海外"}%>
            </div>
          </div>
        </div>
        <!--コミュニティ説明-->
        <div class="field">
          <div class="description_label">
            <%= f.label :コミュニティ説明 %><br />
          </div>
          <div class="description_input_outside">
            <div class="description_input_inner">
          	   <textarea name="content" class="description_textarea"></textarea>
            </div>
          </div>
        </div>
        <!--画像ファイル選択-->
        <div class="field">
          <div class="community_pic_label">
            <%= f.label :コミュニティ画像 %><br/>
          </div>
          <div class="community_pic_input_outside">
            <div class="community_pic_input_inner">
              <%= f.file_field :image_name %>
            </div>
          </div>
        </div>
        <!--登録ボタン-->
        <div class="actions">
          <%= f.submit "新規登録" , class:'login_button'%>
        </div>
      <% end %>
    </div>
  </div>
</div>